export default [
  { ccode: 'AU', cname: 'Australia' },
  { ccode: 'AT', cname: 'Austria' },
  { ccode: 'BD', cname: 'Bangladesh' },
  { ccode: 'BY', cname: 'Belarus' },
  { ccode: 'BE', cname: 'Belgium' },
  { ccode: 'BA', cname: 'Bosnia And Herzegovina' },
  { ccode: 'BR', cname: 'Brazil' },
  { ccode: 'BG', cname: 'Bulgaria' },
  { ccode: 'CA', cname: 'Canada' },
  { ccode: 'KY', cname: 'Cayman Islands' },
  { ccode: 'CF', cname: 'Central African Republic' },
  { ccode: 'CL', cname: 'Chile' },
  { ccode: 'CN', cname: 'China' },
  { ccode: 'CO', cname: 'Colombia' },
  { ccode: 'CG', cname: 'Congo' },
  { ccode: 'CD', cname: 'Congo, Democratic Republic' },
  { ccode: 'CR', cname: 'Costa Rica' },
  { ccode: 'HR', cname: 'Croatia' },
  { ccode: 'CU', cname: 'Cuba' },
  { ccode: 'CY', cname: 'Cyprus' },
  { ccode: 'CZ', cname: 'Czech Republic' },
  { ccode: 'DK', cname: 'Denmark' },
  { ccode: 'EG', cname: 'Egypt' },
  { ccode: 'EE', cname: 'Estonia' },
  { ccode: 'ET', cname: 'Ethiopia' },
  { ccode: 'FO', cname: 'Faroe Islands' },
  { ccode: 'FI', cname: 'Finland' },
  { ccode: 'FR', cname: 'France' },
  { ccode: 'GE', cname: 'Georgia' },
  { ccode: 'DE', cname: 'Germany' },
  { ccode: 'GR', cname: 'Greece' },
  { ccode: 'GL', cname: 'Greenland' },
  { ccode: 'GD', cname: 'Grenada' },
  { ccode: 'GP', cname: 'Guadeloupe' },
  { ccode: 'GT', cname: 'Guatemala' },
  { ccode: 'HT', cname: 'Haiti' },
  { ccode: 'HK', cname: 'Hong Kong' },
  { ccode: 'HU', cname: 'Hungary' },
  { ccode: 'IS', cname: 'Iceland' },
  { ccode: 'IN', cname: 'India' },
  { ccode: 'ID', cname: 'Indonesia' },
  { ccode: 'IR', cname: 'Iran, Islamic Republic Of' },
  { ccode: 'IQ', cname: 'Iraq' },
  { ccode: 'IE', cname: 'Ireland' },
  { ccode: 'IL', cname: 'Israel' },
  { ccode: 'IT', cname: 'Italy' },
  { ccode: 'JM', cname: 'Jamaica' },
  { ccode: 'JP', cname: 'Japan' },
  { ccode: 'KZ', cname: 'Kazakhstan' },
  { ccode: 'KR', cname: 'Korea' },
  { ccode: 'KG', cname: 'Kyrgyzstan' },
  { ccode: 'LA', cname: "Lao People's Democratic Republic" },
  { ccode: 'LV', cname: 'Latvia' },
  { ccode: 'LT', cname: 'Lithuania' },
  { ccode: 'MK', cname: 'Macedonia' },
  { ccode: 'MY', cname: 'Malaysia' },
  { ccode: 'MX', cname: 'Mexico' },
  { ccode: 'MD', cname: 'Moldova' },
  { ccode: 'NL', cname: 'Netherlands' },
  { ccode: 'NO', cname: 'Norway' },
  { ccode: 'PK', cname: 'Pakistan' },
  { ccode: 'PH', cname: 'Philippines' },
  { ccode: 'PL', cname: 'Poland' },
  { ccode: 'PT', cname: 'Portugal' },
  { ccode: 'PR', cname: 'Puerto Rico' },
  { ccode: 'QA', cname: 'Qatar' },
  { ccode: 'RO', cname: 'Romania' },
  { ccode: 'RU', cname: 'Russian Federation' },
  { ccode: 'SA', cname: 'Saudi Arabia' },
  { ccode: 'RS', cname: 'Serbia' },
  { ccode: 'SG', cname: 'Singapore' },
  { ccode: 'SK', cname: 'Slovakia' },
  { ccode: 'SI', cname: 'Slovenia' },
  { ccode: 'ES', cname: 'Spain' },
  { ccode: 'SZ', cname: 'Swaziland' },
  { ccode: 'SE', cname: 'Sweden' },
  { ccode: 'CH', cname: 'Switzerland' },
  { ccode: 'TW', cname: 'Taiwan' },
  { ccode: 'TH', cname: 'Thailand' },
  { ccode: 'TR', cname: 'Turkey' },
  { ccode: 'TM', cname: 'Turkmenistan' },
  { ccode: 'UA', cname: 'Ukraine' },
  { ccode: 'AE', cname: 'United Arab Emirates' },
  { ccode: 'GB', cname: 'United Kingdom' },
  { ccode: 'US', cname: 'United States' },
  { ccode: 'UZ', cname: 'Uzbekistan' },
  { ccode: 'VE', cname: 'Venezuela' },
  { ccode: 'ZW', cname: 'Zimbabwe' },
];
